# Assignment 5 - numpy and pandas

## Section A — Short Theory Questions

### 1. Differentiate between quantitative and qualitative data with examples.

**Quantitative data** is numerical data that can be measured and counted. Example: height, weight, marks obtained, age.

**Qualitative data** is descriptive, non-numerical data that represents categories or characteristics. Example: gender, color, city name, blood group.

---

### 2. What is the difference between mean, median, and mode? When would median be preferred over mean?

- **Mean**: The average of all values (sum of values divided by count).
- **Median**: The middle value when data is arranged in order.
- **Mode**: The most frequently occurring value in the dataset.

**Median is preferred over mean** when the dataset contains outliers or is skewed, since extreme values heavily affect the mean but have little effect on the median.

---

### 3. What do variance and standard deviation measure, and how are they related?

**Variance** measures how spread out the data values are from the mean (average of squared differences from the mean).

**Standard deviation** is the square root of variance, and it expresses the spread in the same unit as the original data, making it easier to interpret.

They are related as: **Standard Deviation = √Variance**

---

### 4. Explain Z-score and how it is used to detect outliers.

A **Z-score** tells us how many standard deviations a data point is away from the mean. It is calculated as:

Z = (x - mean) / standard deviation

A value is typically considered an **outlier** if its Z-score is greater than +3 or less than -3, meaning it lies far away from the rest of the data.

## Section B - Task 1: Mean, Median, Mode

In [1]:
marks = [56, 78, 90, 45, 78, 88, 67, 92, 78, 60]

n = len(marks)
mean_manual = sum(marks) / n

sorted_marks = sorted(marks)
mid = n // 2
median_manual = (sorted_marks[mid-1] + sorted_marks[mid]) / 2 if n % 2 == 0 else sorted_marks[mid]

mode_manual = max(set(marks), key=marks.count)

import statistics as stats
mean_builtin = stats.mean(marks)
median_builtin = stats.median(marks)
mode_builtin = stats.mode(marks)

print("Manual -> Mean:", mean_manual, "Median:", median_manual, "Mode:", mode_manual)
print("Built-in -> Mean:", mean_builtin, "Median:", median_builtin, "Mode:", mode_builtin)

Manual -> Mean: 73.2 Median: 78.0 Mode: 78
Built-in -> Mean: 73.2 Median: 78.0 Mode: 78


## Section B - Task 2: Variance, Standard Deviation, Coefficient of Variation

In [2]:
variance = stats.variance(marks)
std_dev = stats.stdev(marks)
cv = (std_dev / mean_builtin) * 100

print("Variance:", variance)
print("Standard Deviation:", std_dev)
print("Coefficient of Variation:", cv, "%")

Variance: 247.51111111111112
Standard Deviation: 15.732485852881327
Coefficient of Variation: 21.49246701213296 %


## Section B - Task 3: Z-Scores and Outlier Detection

In [3]:
import numpy as np

marks_arr = np.array(marks)
z_scores = (marks_arr - mean_builtin) / std_dev

outliers = marks_arr[np.abs(z_scores) > 3]

print("Z-scores:", z_scores)
print("Outliers:", outliers)

Z-scores: [-1.09327923  0.30510118  1.06785413 -1.79246943  0.30510118  0.94072864
 -0.39408902  1.19497962  0.30510118 -0.83902825]
Outliers: []


## Section B - Task 4: Correlation Coefficient - Study Hours vs Marks

In [4]:
study_hours = [2, 4, 5, 1, 4, 5, 3, 6, 4, 2]

correlation = np.corrcoef(study_hours, marks)[0, 1]
print("Correlation coefficient:", correlation)

Correlation coefficient: 0.9884539819342438


## Section 2 - Task 1: NumPy Arrays - Creation, Reshape, Indexing, Slicing

In [5]:
arr_from_list = np.array([1, 2, 3, 4, 5, 6])
arr_arange = np.arange(1, 13)
arr_random = np.random.randint(1, 100, 6)

reshaped = arr_arange.reshape(3, 4)

print("From list:", arr_from_list)
print("Arange:", arr_arange)
print("Random:", arr_random)
print("Reshaped:\n", reshaped)

print("Indexing element:", reshaped[1, 2])
print("Slicing row:", reshaped[0, :])
print("Slicing column:", reshaped[:, 1])

From list: [1 2 3 4 5 6]
Arange: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Random: [39 27 11 97 44  7]
Reshaped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Indexing element: 7
Slicing row: [1 2 3 4]
Slicing column: [ 2  6 10]


## Section 2 - Task 2: Arithmetic Operations and Universal Functions

In [6]:
arr = np.array([4, 9, 16, 25, 36])

print("Add 10:", arr + 10)
print("Multiply by 2:", arr * 2)
print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))

Add 10: [14 19 26 35 46]
Multiply by 2: [ 8 18 32 50 72]
Square root: [2. 3. 4. 5. 6.]
Exponential: [5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10
 4.31123155e+15]
Max: 36
Min: 4


## Section 2 - Task 3: Pandas DataFrame - Basic Info

In [7]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal"],
    "Subject": ["Math", "Physics", "Math", "Chemistry", "Physics"],
    "Marks": [85, 90, 78, 92, 60]
})

print(df.head())
print("Shape:", df.shape)
print("Dtypes:\n", df.dtypes)

     Name    Subject  Marks
0     Ali       Math     85
1    Sara    Physics     90
2   Ahmed       Math     78
3  Ayesha  Chemistry     92
4   Bilal    Physics     60
Shape: (5, 3)
Dtypes:
 Name         str
Subject      str
Marks      int64
dtype: object


## Section 2 - Task 4: Data Selection and Filtering

In [8]:
print(df[df["Marks"] > 80])
print(df.loc[0:2, ["Name", "Marks"]])
print(df.iloc[1:4, 0:2])

     Name    Subject  Marks
0     Ali       Math     85
1    Sara    Physics     90
3  Ayesha  Chemistry     92
    Name  Marks
0    Ali     85
1   Sara     90
2  Ahmed     78
     Name    Subject
1    Sara    Physics
2   Ahmed       Math
3  Ayesha  Chemistry


## Section 2 - Task 5: Handling Missing Data

In [9]:
df_missing = df.copy()
df_missing.loc[2, "Marks"] = None
df_missing.loc[4, "Subject"] = None

print("Null values:\n", df_missing.isnull().sum())

df_filled = df_missing.fillna({"Marks": df_missing["Marks"].mean(), "Subject": "Unknown"})
print(df_filled)

df_dropped = df_missing.dropna()
print(df_dropped)

Null values:
 Name       0
Subject    1
Marks      1
dtype: int64
     Name    Subject  Marks
0     Ali       Math  85.00
1    Sara    Physics  90.00
2   Ahmed       Math  81.75
3  Ayesha  Chemistry  92.00
4   Bilal    Unknown  60.00
     Name    Subject  Marks
0     Ali       Math   85.0
1    Sara    Physics   90.0
3  Ayesha  Chemistry   92.0


## Section 2 - Task 6: Groupby - Average Marks per Subject

In [10]:
avg_marks = df.groupby("Subject")["Marks"].mean()
print(avg_marks)

Subject
Chemistry    92.0
Math         81.5
Physics      75.0
Name: Marks, dtype: float64


## Section 2 - Task 7: Merge and Concatenate DataFrames

In [11]:
df1 = pd.DataFrame({"Name": ["Ali", "Sara"], "Marks": [85, 90]})
df2 = pd.DataFrame({"Name": ["Ahmed", "Ayesha"], "Marks": [78, 92]})

concatenated = pd.concat([df1, df2], ignore_index=True)
print("Concatenated:\n", concatenated)

df3 = pd.DataFrame({"Name": ["Ali", "Sara"], "City": ["Lahore", "Karachi"]})
merged = pd.merge(df1, df3, on="Name")
print("Merged:\n", merged)

Concatenated:
      Name  Marks
0     Ali     85
1    Sara     90
2   Ahmed     78
3  Ayesha     92
Merged:
    Name  Marks     City
0   Ali     85   Lahore
1  Sara     90  Karachi
