# EDA in pythonm

In [1]:
! pip install numpy pandas matplotlib seaborn

  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.4 MB 4.9 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.4 MB 8.0 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.4 MB 10.6 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.4 MB 9.4 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 10.9 MB/s  0:00:01
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   --------------------- ------------------ 5.2/9.8 MB 25.9 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 24.2 MB/s  0:00:00
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   -------------------- -----------------

In [6]:
## Importing EDA libraries
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## timestamp 
import time
print ("last update: " , time.asctime())

# filter warnings
import warnings as w
w.filterwarnings('ignore')

last update:  Wed Jul 22 09:55:28 2026


## Understanding numpy fundamentals


### creating an array 

In [7]:
arr = np.array([3,4,5,3,3,8,6,9,5])
arr 

array([3, 4, 5, 3, 3, 8, 6, 9, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
a = np.array([1,2,3,4])
a.ndim

1

In [16]:
b = np.array([[1,2,3],[4,5,6]])
b.ndim , b



(2,
 array([[1, 2, 3],
        [4, 5, 6]]))

In [18]:
c = np.array([[2,4,5,6,7,8,9],[1,3,4,5,6,7,8]])
c, c.ndim

(array([[2, 4, 5, 6, 7, 8, 9],
        [1, 3, 4, 5, 6, 7, 8]]),
 2)

In [23]:
d = np.array(
    [
        [
            
            [2,3,4], [5,6,7]
        ],
        [
            [4,5,6],[9,8,7]
            ]
    ]
)
d , d.ndim
d.shape


(2, 2, 3)

In [29]:
e = np.array(
    [
        [
            [1,2,3,4,5],[6,7,8,9,10], [1,3,5,7,9]
        ],
        [
            [9,8,7,6,5],[4,3,2,1,0],[9,7,5,3,1]
        ]
    ]
)
e, e.ndim, e.shape

(2, 3, 5)

### attributes

In [30]:
a.ndim , b.ndim , c.ndim , d.ndim

(1, 2, 2, 3)

In [31]:
a.shape , b.shape , d.shape 

((4,), (2, 3), (2, 2, 3))

In [32]:
a.size , b.size , c.size , d.size

(4, 6, 14, 12)

In [33]:
a.dtype , b.dtype , c.dtype , d.dtype , e.dtype

(dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'))

shape: The dimensions of the array (e. g , number of rows and columns).
size: The total count of items packed inside the array
dtype: The kind of data stored (like whole numbers, decimals, or text).
itemsize: The memory space a single item occupies in bytes.
nbytes: The total memory space the entire array takes up

### array indexing and slicing 

In [37]:
a 

array([1, 2, 3, 4])

In [39]:
a[2] , a[1:3]

(np.int64(3), array([2, 3]))

In [40]:
d

array([[[2, 3, 4],
        [5, 6, 7]],

       [[4, 5, 6],
        [9, 8, 7]]])

In [45]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b[1]

array([4, 5, 6])

### reshape 

In [49]:
b.shape

(2, 3)

In [53]:
b = b.reshape(6)
b

array([1, 2, 3, 4, 5, 6])

In [60]:
x = np.array([1,2,3,4,6,7,8,9,45,42,356,34,6,535,23,54])
len(x)


16

### array operation 

### broadcasting

### useful function in numpy

In [69]:
y = np.ones((10,5) ,dtype ='int')
y= y*2
y

In [70]:
p = numbers = np.linspace(0, 100, num=5000)


In [71]:
q =p.reshape(250,20)

In [ ]:
r = reshape (5,2,1,1,2,1,5,2,5,5)