<h1 style="text-align:center; color:#2E86C1; background-color:#EBF5FB; padding:20px; border-radius:10px; border:2px solid #2E86C1;">
📘 Complete NumPy Course — From Basics to Advanced
</h1>
<h3 style="text-align:center; color:#555;">Trainer: <b>Engr Aamir Jamil</b></h3>
<hr>

## 📑 About this Notebook
This notebook is designed to teach **NumPy** step by step, in very simple language.

- Every topic has a **markdown explanation** first, then **small code cells**.
- Code cells are kept **short and simple** — one idea per cell.
- By the end, you will understand almost **everything about NumPy**.

### Topics Covered
1. Introduction to NumPy
2. Installing & Importing NumPy
3. NumPy Arrays vs Python Lists
4. Creating Arrays
5. Array Attributes
6. Data Types in NumPy
7. Indexing
8. Slicing
9. Reshaping Arrays
10. Flattening Arrays
11. Joining Arrays
12. Splitting Arrays
13. Arithmetic Operations
14. Broadcasting
15. Aggregate / Statistical Functions
16. Sorting Arrays
17. Searching Arrays
18. Boolean Masking & Filtering
19. Fancy Indexing
20. Copy vs View
21. Iterating Arrays
22. Stacking Arrays
23. Universal Functions (ufuncs)
24. Linear Algebra
25. Random Module
26. Set Operations
27. Handling Missing Values (NaN)
28. Saving & Loading Arrays
29. Working with Dates (datetime64)
30. Structured Arrays
31. Vectorization & Performance
32. Conclusion & Practice Tips


## 1️⃣ Introduction to NumPy

**NumPy** stands for **Numerical Python**.

- It is a Python library used for working with **arrays** (lists of numbers).
- It is much **faster** than normal Python lists because it uses less memory and works with C code internally.
- It is the foundation of many other libraries like Pandas, Matplotlib, Scikit-learn, TensorFlow etc.

### Why use NumPy instead of normal Python lists?
| Python List | NumPy Array |
|---|---|
| Slow for large data | Fast (vectorized operations) |
| Can hold mixed data types | Usually holds one data type |
| No built-in math operations | Has built-in math functions |
| Uses more memory | Uses less memory |


## 2️⃣ Installing and Importing NumPy

If NumPy is not installed, you can install it using pip:
```
pip install numpy
```

To use NumPy in your code, you must **import** it first. We usually import it with a short name `np` so we don't have to type "numpy" every time.


In [1]:
# Installing numpy (run only if not already installed)
# !pip install numpy

In [2]:
# Importing numpy
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.4


## 3️⃣ NumPy Arrays vs Python Lists

A **NumPy array** looks similar to a Python list, but it behaves very differently — especially with math operations.


In [3]:
# Python list
py_list = [1, 2, 3, 4]
print(py_list * 2)   # This repeats the list, does not multiply each element

[1, 2, 3, 4, 1, 2, 3, 4]


In [4]:
# NumPy array
np_array = np.array([1, 2, 3, 4])
print(np_array * 2)   # This multiplies each element by 2

[2 4 6 8]


## 4️⃣ Creating Arrays

There are many ways to create NumPy arrays. Let's learn them one by one.

### 4.1 Using `np.array()`
This converts a Python list (or list of lists) into a NumPy array.


In [5]:
# 1D array
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [6]:
# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
# 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 4.2 Using `np.zeros()`, `np.ones()`, `np.full()`

- `np.zeros(shape)` → creates an array filled with 0s
- `np.ones(shape)` → creates an array filled with 1s
- `np.full(shape, value)` → creates an array filled with a custom value


In [8]:
zeros_arr = np.zeros((2, 3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
ones_arr = np.ones((3, 2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
full_arr = np.full((2, 2), 7)
print(full_arr)

[[7 7]
 [7 7]]


### 4.3 Using `np.arange()`

Similar to Python's `range()`, but returns a NumPy array.
Syntax: `np.arange(start, stop, step)`


In [11]:
arr_range = np.arange(0, 10, 2)
print(arr_range)

[0 2 4 6 8]


### 4.4 Using `np.linspace()`

Creates evenly spaced numbers between a start and stop value.
Syntax: `np.linspace(start, stop, num_of_values)`


In [12]:
arr_lin = np.linspace(0, 1, 5)
print(arr_lin)

[0.   0.25 0.5  0.75 1.  ]


### 4.5 Identity Matrix — `np.eye()` / `np.identity()`

Creates a square matrix with 1s on the diagonal and 0s everywhere else.


In [13]:
identity_arr = np.eye(3)
print(identity_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 4.6 Random Arrays (quick preview)

We will study the `random` module in detail later, but here is a quick example.


In [14]:
random_arr = np.random.rand(2, 2)   # random values between 0 and 1
print(random_arr)

[[0.41771584 0.56980854]
 [0.9168577  0.61137488]]


## 5️⃣ Array Attributes

Every NumPy array has some useful attributes (properties) that tell us about the array.

| Attribute | Meaning |
|---|---|
| `ndim` | Number of dimensions |
| `shape` | Size along each dimension |
| `size` | Total number of elements |
| `dtype` | Data type of elements |
| `itemsize` | Size (in bytes) of each element |


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Dimensions:", arr.ndim)

Array:
 [[1 2 3]
 [4 5 6]]
Dimensions: 2


In [16]:
print("Shape:", arr.shape)   # (rows, columns)

Shape: (2, 3)


In [17]:
print("Size:", arr.size)     # total elements

Size: 6


In [18]:
print("Data type:", arr.dtype)

Data type: int64


In [19]:
print("Item size (bytes):", arr.itemsize)

Item size (bytes): 8


## 6️⃣ Data Types in NumPy

NumPy arrays can hold different data types like `int32`, `int64`, `float64`, `bool`, `str`, etc.

You can check or set the data type using the `dtype` parameter.


In [20]:
arr_int = np.array([1, 2, 3], dtype='int32')
print(arr_int, arr_int.dtype)

[1 2 3] int32


In [21]:
arr_float = np.array([1, 2, 3], dtype='float64')
print(arr_float, arr_float.dtype)

[1. 2. 3.] float64


In [22]:
# Converting data type of an existing array using astype()
arr_bool = arr_int.astype('float32')
print(arr_bool, arr_bool.dtype)

[1. 2. 3.] float32


## 7️⃣ Indexing

Indexing means accessing a specific element from an array using its position (index).
Indexing starts from **0**.


In [23]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])    # first element

10


In [24]:
print(arr[-1])   # last element

50


In [25]:
# Indexing in 2D array: arr[row, column]
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[1, 2])   # row 1, column 2

6


## 8️⃣ Slicing

Slicing means taking a **range** of elements from an array.
Syntax: `arr[start:stop:step]`


In [26]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])     # elements from index 1 to 3

[20 30 40]


In [27]:
print(arr[:3])      # first 3 elements

[10 20 30]


In [28]:
print(arr[::2])     # every second element

[10 30 50]


In [29]:
# Slicing a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0:2, 1:3])   # rows 0-1, columns 1-2

[[2 3]
 [5 6]]


## 9️⃣ Reshaping Arrays

`reshape()` changes the shape of an array **without changing its data**.
The total number of elements must remain the same.


In [30]:
arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

In [31]:
reshaped = arr.reshape(3, 4)   # 3 rows, 4 columns
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
reshaped2 = arr.reshape(2, 3, 2)   # 3D shape
print(reshaped2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## 🔟 Flattening Arrays

Flattening converts a multi-dimensional array into a **1D array**.

- `flatten()` → returns a **copy**
- `ravel()` → returns a **view** (shares memory with original when possible)


In [33]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
flat = arr2d.flatten()
print(flat)

[1 2 3 4 5 6]


In [34]:
raveled = arr2d.ravel()
print(raveled)

[1 2 3 4 5 6]


## 1️⃣1️⃣ Joining Arrays

We can join two or more arrays using `np.concatenate()`.


In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
joined = np.concatenate((a, b))
print(joined)

[1 2 3 4 5 6]


In [36]:
# Joining 2D arrays along rows (axis=0) or columns (axis=1)
a2 = np.array([[1, 2], [3, 4]])
b2 = np.array([[5, 6], [7, 8]])
print(np.concatenate((a2, b2), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
print(np.concatenate((a2, b2), axis=1))

[[1 2 5 6]
 [3 4 7 8]]


## 1️⃣2️⃣ Splitting Arrays

`np.array_split()` splits one array into multiple smaller arrays.


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.array_split(arr, 3)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [39]:
# hsplit -> split horizontally, vsplit -> split vertically
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.hsplit(arr2d, 2))

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


## 1️⃣3️⃣ Arithmetic Operations

NumPy allows element-wise arithmetic directly using operators, without loops.


In [40]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)

Addition: [5 7 9]


In [41]:
print("Subtraction:", b - a)

Subtraction: [3 3 3]


In [42]:
print("Multiplication:", a * b)

Multiplication: [ 4 10 18]


In [43]:
print("Division:", b / a)

Division: [4.  2.5 2. ]


In [44]:
print("Power:", a ** 2)

Power: [1 4 9]


In [45]:
print("Modulus:", b % a)

Modulus: [0 1 0]


## 1️⃣4️⃣ Broadcasting

Broadcasting lets NumPy perform operations on arrays of **different shapes** by automatically expanding the smaller array.

### Rule (simple version)
If the shapes don't match, NumPy tries to "stretch" the smaller array so shapes become compatible.


In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

print(arr + scalar)   # scalar is broadcast to every element

[[11 12 13]
 [14 15 16]]


In [47]:
row = np.array([1, 0, 1])
print(arr + row)   # row is broadcast to every row of arr

[[2 2 4]
 [5 5 7]]


## 1️⃣5️⃣ Aggregate / Statistical Functions

These functions summarize data — for example finding total, average, minimum, etc.


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))

Sum: 21


In [49]:
print("Sum along columns (axis=0):", np.sum(arr, axis=0))
print("Sum along rows (axis=1):", np.sum(arr, axis=1))

Sum along columns (axis=0): [5 7 9]
Sum along rows (axis=1): [ 6 15]


In [50]:
print("Min:", np.min(arr))
print("Max:", np.max(arr))

Min: 1
Max: 6


In [51]:
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))

Mean: 3.5
Median: 3.5


In [52]:
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))

Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665


In [53]:
print("Index of Max value:", np.argmax(arr))
print("Index of Min value:", np.argmin(arr))

Index of Max value: 5
Index of Min value: 0


## 1️⃣6️⃣ Sorting Arrays

`np.sort()` returns a **sorted copy** of the array.


In [54]:
arr = np.array([3, 1, 4, 1, 5, 9, 2])
print(np.sort(arr))

[1 1 2 3 4 5 9]


In [55]:
# Sorting a 2D array (sorts each row by default)
arr2d = np.array([[3, 1], [2, 4]])
print(np.sort(arr2d))

[[1 3]
 [2 4]]


## 1️⃣7️⃣ Searching Arrays

`np.where()` finds the **index positions** where a condition is true.


In [56]:
arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr > 25)
print(result)

(array([2, 3, 4]),)


In [57]:
# searchsorted() finds the index where a value should be inserted to keep the array sorted
arr = np.array([1, 3, 5, 7])
print(np.searchsorted(arr, 4))

2


## 1️⃣8️⃣ Boolean Masking & Filtering

We can filter arrays using conditions. This is called **boolean indexing / masking**.


In [58]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25
print(mask)

[False False  True  True  True]


In [59]:
print(arr[mask])   # only elements where mask is True

[30 40 50]


In [60]:
# Direct filtering without storing mask separately
print(arr[arr % 20 == 0])

[20 40]


## 1️⃣9️⃣ Fancy Indexing

Fancy indexing means passing a **list of indexes** to select multiple elements at once.


In [61]:
arr = np.array([10, 20, 30, 40, 50])
indexes = [0, 2, 4]
print(arr[indexes])

[10 30 50]


In [62]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[[0, 2]])   # select row 0 and row 2

[[1 2 3]
 [7 8 9]]


## 2️⃣0️⃣ Copy vs View

- **Copy**: A completely new array. Changes in the copy do **not** affect the original.
- **View**: Shares memory with the original array. Changes in the view **do** affect the original.


In [63]:
arr = np.array([1, 2, 3])
copy_arr = arr.copy()
copy_arr[0] = 100

print("Original:", arr)
print("Copy:", copy_arr)

Original:

 [1 2 3]
Copy: [100   2   3]


In [64]:
view_arr = arr.view()
view_arr[0] = 100

print("Original:", arr)   # original also changes!
print("View:", view_arr)

Original: [100   2   3]
View: [100   2   3]


## 2️⃣1️⃣ Iterating Arrays

We can loop through NumPy arrays using a normal `for` loop, or use `np.nditer()` for multi-dimensional arrays.


In [65]:
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


In [66]:
arr2d = np.array([[1, 2], [3, 4]])
for x in np.nditer(arr2d):
    print(x)

1
2
3
4


## 2️⃣2️⃣ Stacking Arrays

Stacking joins arrays along a **new axis**.

- `np.vstack()` → stack vertically (row-wise)
- `np.hstack()` → stack horizontally (column-wise)
- `np.dstack()` → stack depth-wise (along a third axis)


In [67]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]


In [68]:
print(np.hstack((a, b)))

[1 2 3 4 5 6]


In [69]:
print(np.dstack((a, b)))

[[[1 4]
  [2 5]
  [3 6]]]


## 2️⃣3️⃣ Universal Functions (ufuncs)

Ufuncs are fast, built-in functions that operate **element-wise** on arrays. They are much faster than Python loops.


In [70]:
arr = np.array([1, 4, 9, 16])
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [71]:
print(np.exp(arr))     # e^x for each element

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [72]:
print(np.log(arr))     # natural log

[0.         1.38629436 2.19722458 2.77258872]

In [73]:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]

In [74]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.add(a, b))
print(np.subtract(a, b))

[5 7 9]


[-3 -3 -3]


## 2️⃣4️⃣ Linear Algebra

NumPy has a special module `np.linalg` for matrix/linear algebra operations.


In [75]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix Multiplication:\n", np.dot(a, b))

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [76]:
print("Matrix Multiplication (matmul):\n", np.matmul(a, b))

Matrix Multiplication (matmul):


 [[19 22]
 [43 50]]


In [77]:
print("Transpose:\n", a.T)

Transpose:
 [[1 3]
 [2 4]]


In [78]:
print("Determinant:", np.linalg.det(a))

Determinant:

 -2.0000000000000004


In [79]:
print("Inverse:\n", np.linalg.inv(a))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [80]:
# Solving linear equations: ax = b
coeff = np.array([[3, 1], [1, 2]])
result = np.array([9, 8])
solution = np.linalg.solve(coeff, result)
print("Solution:", solution)

Solution:

 [2. 3.]


## 2️⃣5️⃣ Random Module

The `np.random` module is used to generate random numbers and arrays.


In [81]:
# Random float between 0 and 1
print(np.random.rand())

0.7775158929798668


In [82]:
# Random array of floats
print(np.random.rand(2, 3))

[[0.06203172 0.83431684 0.35283478]
 [0.44595761 0.79797357 0.86768098]]


In [83]:
# Random integers between a range
print(np.random.randint(1, 100, size=(2, 3)))

[[75 92 80]
 [89 92  5]]


In [84]:
# Setting a seed makes random numbers reproducible
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


In [85]:
# Random choice from a list
arr = np.array([10, 20, 30, 40])
print(np.random.choice(arr, size=2))

[10 10]


In [86]:
# Shuffle an array (in place)
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[5 1 4 3 2]


## 2️⃣6️⃣ Set Operations

NumPy provides functions similar to set operations in mathematics.


In [87]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print("Union:", np.union1d(a, b))

Union: [1 2 3 4 5 6]


In [88]:
print("Intersection:", np.intersect1d(a, b))

Intersection: [3 4]


In [89]:
print("Difference (a - b):", np.setdiff1d(a, b))

Difference (a - b): [1 2]


In [90]:
# unique() removes duplicate values
arr = np.array([1, 1, 2, 2, 3, 3])
print("Unique values:", np.unique(arr))

Unique values: [1 2 3]


## 2️⃣7️⃣ Handling Missing Values (NaN)

`NaN` means **Not a Number** and is used to represent missing values.


In [91]:
arr = np.array([1, 2, np.nan, 4])
print(arr)

[ 1.  2. nan  4.]


In [92]:
print(np.isnan(arr))   # check which values are NaN

[False False  True False]


In [93]:
# Functions that ignore NaN values while calculating
print(np.nanmean(arr))
print(np.nansum(arr))

2.3333333333333335
7.0


## 2️⃣8️⃣ Saving and Loading Arrays

NumPy arrays can be saved to disk and loaded back later.

- `np.save()` / `np.load()` → binary `.npy` format
- `np.savetxt()` / `np.loadtxt()` → text format (like `.csv`)


In [94]:
arr = np.array([1, 2, 3, 4])
np.save('my_array.npy', arr)   # saves file

In [95]:
loaded = np.load('my_array.npy')
print(loaded)

[1 2 3 4]

In [96]:
np.savetxt('my_array.csv', arr, delimiter=',')
loaded_csv = np.loadtxt('my_array.csv', delimiter=',')
print(loaded_csv)

[1. 2. 3. 4.]


## 2️⃣9️⃣ Working with Dates (datetime64)

NumPy can work with dates using the `datetime64` data type.


In [97]:
date = np.datetime64('2024-01-01')
print(date)

2024-01-01


In [98]:
# Creating a range of dates
dates = np.arange('2024-01-01', '2024-01-10', dtype='datetime64[D]')
print(dates)

['2024-01-01' '2024-01-02' '2024-01-03' '2024-01-04' '2024-01-05'
 '2024-01-06' '2024-01-07' '2024-01-08' '2024-01-09']


In [99]:
# Adding days to a date
new_date = date + np.timedelta64(5, 'D')
print(new_date)

2024-01-06


## 3️⃣0️⃣ Structured Arrays

Structured arrays let each element hold **multiple fields** (like a mini table row), similar to a database record.


In [100]:
data = np.array([('Ali', 25), ('Sara', 30)],
                 dtype=[('name', 'U10'), ('age', 'i4')])
print(data)

[('Ali', 25) ('Sara', 30)]


In [101]:
print(data['name'])
print(data['age'])

['Ali' 'Sara']
[25 30]


## 3️⃣1️⃣ Vectorization & Performance

**Vectorization** means replacing explicit loops with array operations. It is much faster because NumPy runs operations in optimized C code internally.


In [102]:
import time

size = 1_000_000
a = list(range(size))
b = list(range(size))

start = time.time()
result = [a[i] + b[i] for i in range(size)]
print("Python loop time:", time.time() - start)

Python loop time: 0.32386183738708496


In [103]:
a_np = np.array(a)
b_np = np.array(b)

start = time.time()
result_np = a_np + b_np
print("NumPy vectorized time:", time.time() - start)

NumPy vectorized time: 0.046866655349731445


## 3️⃣2️⃣ Conclusion & Practice Tips

🎉 Congratulations! You have covered all the major topics of NumPy:

- Array creation, attributes, and data types
- Indexing, slicing, reshaping, and joining
- Arithmetic, broadcasting, and universal functions
- Aggregation, sorting, searching, and filtering
- Copy vs view, iterating, and stacking
- Linear algebra and random number generation
- Set operations, NaN handling, saving/loading
- Dates, structured arrays, and vectorization

### 💡 Tips to Master NumPy
1. Practice writing small code snippets daily.
2. Try to solve problems **without loops** — use vectorized operations.
3. Read the shape and dtype of every array you create.
4. Use `help(np.function_name)` inside Jupyter to see documentation.
5. Move on to **Pandas** next — it is built on top of NumPy!

---
<p style="text-align:center; color:gray;">Notebook prepared by <b>Engr Aamir Jamil</b></p>
